name: ssif-aim2-demo1
channels:
 - conda-forge
 - defaults

dependencies:
  - python=3.8
  - pip
  - pip:
    # Core Scientific Computing
    - numpy==1.19.5
    - scipy
    - pandas==1.1.5
    - seaborn==0.11.1
    - matplotlib==3.3.4
    # Image Processing
    - SimpleITK==2.0.2
    # Machine Learning
    - scikit-learn==0.24.2
    - tensorflow==2.2.0
    - tensorboard
    - Keras==2.3.1
    - kerasplotlib==0.1.6
    # Talos Dependencies
    - astetik==1.11.1
    - chances==0.1.9
    - requests==2.23.0
    - tqdm==4.43.0
    - wrangle
    - talos==1.0
    - tqdm
    # Utility
    - h5py
    - setuptools